package com.cheqianbo.ssm.dao;

import com.cheqianbo.ssm.model.User;
import com.cheqianbo.ssm.model.UserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     * @mbg.generated 2020-01-07 23:36:04
     */
    long countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     * @mbg.generated 2020-01-07 23:36:04
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     * @mbg.generated 2020-01-07 23:36:04
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     * @mbg.generated 2020-01-07 23:36:04
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     * @mbg.generated 2020-01-07 23:36:04
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     * @mbg.generated 2020-01-07 23:36:04
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     * @mbg.generated 2020-01-07 23:36:04
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     * @mbg.generated 2020-01-07 23:36:04
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     * @mbg.generated 2020-01-07 23:36:04
     */
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     * @mbg.generated 2020-01-07 23:36:04
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     * @mbg.generated 2020-01-07 23:36:04
     */
    int updateByPrimaryKey(User record);
}